### ISSUE TITLE
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.

### ISSUE THREAD

**Issue by jahlomp** [WoolDoughnut310/jnaudiostream#1]
According to https://developer.chrome.com/blog/autoplay/, The Autoplay Policy launched in Chrome 66 for audio and video elements blocks media from autoplaying in Chrome.

This affects AudioStreamer's playStream method.

**Comment by WoolDoughnut310** [comment]
Created a new PR: #2
